base_job_name: accelerate-sagemaker-1
ec2_instance_type: ml.g5.48xlarge
iam_role_name: AmazonSageMaker-ExecutionRole
image_uri: 271150355607.dkr.ecr.us-east-1.amazonaws.com/dbpprt_llamamaker:latest
num_machines: 1
profile: default
#py_version: py311
#pytorch_version: 2.2.0
region: us-east-1
#transformers_version: 4.36.0
sagemaker_metrics_file: config/sagemaker_metrics_definition.tsv
#additional_args:
   #use_spot_instances: True
   #max_wait: 86400